#!/bin/bash
# Write a script which displays the list of files from the folder given as parameter, sorted by size.

# ls -- list derictory contents
# -l -- List in long format.
# -S -- sort by file size (largest first)
# $1 -- are positional parameter (first parameter here, folder to check).

ls -lS $1
